[package]
name = "status_bar"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
iced = { version = "0.9.0", features = ["canvas", "tokio", "debug", "image", "glow"] }
iced_native = "0.10.3"
iced_style = "*"
rand = "0.8.5"
serde = { version = "1.0.163", features = ["derive"] }
serde_yaml = "0.9.21"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
time = { version = "0.3.5", features = ["local-offset", "formatting", "parsing" ] }
lazy_static = "1.4.0"
