[build]
default-target = "aarch64-unknown-linux-gnu"
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get --assume-yes install pkg-config libdbus-1-dev:$CROSS_DEB_ARCH libwayland-dev:$CROSS_DEB_ARCH libxkbcommon-dev:$CROSS_DEB_ARCH libwayland-client0:$CROSS_DEB_ARCH"
]

# Fix for https://github.com/cross-rs/cross/issues/1181
[build.env]
volumes = ["__LIB12_DEP=../services"]
