[package]
name = "idle_notify"
description = "Idle timeout service for Mechanix desktop sevices"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
serde.workspace = true
serde_yaml = "0.9.25"
wayland-protocols-async = { git = "https://github.com/mecha-org/wayland-protocols-async.git" }
mechanix-desktop-settings = { path = "../../settings" }
mechanix_system_dbus_client.workspace = true
command = { workspace = true }
events = { path = "../../events" }
logind = { workspace = true }