[package]
name = "mechanix-keyboard"
description = "Onscreen keyboard component for the Mechanix shell"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true 
serde_yaml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tokio.workspace = true
zbus.workspace = true
mctk_core = { workspace = true }
mctk_smithay = { workspace = true }
mctk_macros = { workspace = true }
const_format = "0.2.32"
dirs = "5.0.1"

[package.metadata.deb]
name = "mechanix-keyboard"
depends = "$auto"
assets = [
    # binary
    [
        "../target/release/mechanix-keyboard",
        "/usr/bin/",
        "755",
    ],
    #assets
    [
        "src/assets/**/*",
        "/usr/share/mechanix/shell/keyboard/assets/",
        "644",
    ],

    # settings
    [
        "settings.yml.example",
        "/etc/mechanix/shell/keyboard/settings.yml",
        "644",
    ],
]

