[package]
name = "mechanix-greeter"
description = "Greeter (login or display manager) component for the Mechanix shell"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
anyhow = "1.0.71"
serde = { version = "1.0.163", features = ["derive"] }
serde_yaml = "0.9.21"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
greetd_ipc = { version = "0.9.0", features = ["tokio-codec"] }
tokio = { version = "1.33", features = ["full"] }
mctk_core = { workspace = true }
mctk_smithay = { workspace = true }
mctk_macros = { workspace = true }
smithay-client-toolkit = { workspace = true }
futures = "0.3.30"
