[package]
name = "session"
description = "Idle timeout service for Mechanix desktop sevices"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lock_button = { path = "../lock-button" }
idle_notify = { path = "../idle-notify" }
tokio.workspace = true
anyhow.workspace = true
events = { path = "../../events" }
mechanix-desktop-settings = { path = "../../settings" }
logind = { workspace = true }
zbus.workspace = true
futures.workspace = true
command.workspace = true