[package]
name = "mechanix_desktop_dbus_server"
description = "Zbus interface for Mechanix desktop services"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio.workspace = true
anyhow.workspace = true
zbus = { version = "4.1.2", features = ["tokio"] }
mechanix-sound-ctl = { path = "../../../ctl/sound" }
mechanix-power-ctl = { path = "../../../ctl/power" }
mechanix-desktop-settings = { path = "../settings" }
session = { path = "../handlers/session" }
serde.workspace = true
tracing.workspace = true
serde_yaml = "0.9.25"


[package.metadata.deb]
name = "mechanix_desktop_dbus_server"
depends = "$auto"
assets = [
    # binary
    [
        "../../../target/release/mechanix_desktop_dbus_server",
        "/usr/bin/",
        "755",
    ],
]
