[package]
name = "mechanix-status-bar"
description = "Status bar component for the Mechanix shell"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
anyhow = "1.0.71"
serde = { version = "1.0.163", features = ["derive"] }
serde_yaml = "0.9.21"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
chrono = "0.4.31"
tokio = { version = "1.33", features = ["full"] }
echo_client = { path = "../commons/echo-client"}
zbus = "3.14.1"
wayland-protocols-async = "1.0.0"
mctk_core = { workspace = true }
mctk_smithay = { workspace = true }
mctk_macros = { workspace = true }
mechanix-zbus-client = { workspace = true }

[package.metadata.deb]
name = "mechanix-status-bar"
depends = "$auto"
assets = [
    # binary
    ["../target/release/mechanix-status-bar", "/usr/bin/", "755"],
    #fonts
    ["src/assets/fonts/*", "/usr/share/mechanix-status-bar/assets/fonts/", "644"],
    # battery icons
    ["src/assets/icons/battery/*", "/usr/share/mechanix-status-bar/assets/icons/battery/", "644"],
    # battery-charging icons
    ["src/assets/icons/battery/charging/*", "/usr/share/mechanix-status-bar/assets/icons/battery/charging/", "644"],
    # bluetooth-icons
    ["src/assets/icons/bluetooth/*", "/usr/share/mechanix-status-bar/assets/icons/bluetooth/", "644"],
    # wireless
    ["src/assets/icons/wireless/*", "/usr/share/mechanix-status-bar/assets/icons/wireless/", "644"],
    # settings
    ["settings.yml.example", "/etc/mechanix-gui/shell/status-bar/", "644"],
]