[package]
name = "mechanix-status-bar"
description = "Status bar component for the Mechanix shell"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
anyhow = "1.0.71"
serde = { version = "1.0.163", features = ["derive"] }
serde_yaml = "0.9.21"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
chrono = { workspace = true }
tokio = { version = "1.33", features = ["full"] }
echo_client = { path = "../commons/echo-client" }
zbus = "3.14.1"
wayland-protocols-async = "1.0.0"
mctk_core = { workspace = true }
mctk_smithay = { workspace = true }
mctk_macros = { workspace = true }
mechanix_zbus_client = { workspace = true }

[package.metadata.deb]
name = "mechanix-status-bar"
depends = "$auto"
assets = [
    # binary
    [
        "../target/aarch64-unknown-linux-gnu/release/mechanix-status-bar",
        "/usr/bin/",
        "755",
    ],
    #assets
    [
        "src/assets/**/*",
        "/usr/share/mechanix/shell/status-bar/assets/",
        "644",
    ],

    # settings
    [
        "settings.yml.example",
        "/etc/mechanix/shell/status-bar/settings.yml",
        "644",
    ],
]
